services:
  db:
    image: postgres:15
    container_name: barberflow_postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: clickFila_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: spring_api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    profiles:
      - "app"
    environment:
      # Database injection
      - DB_URL=jdbc:postgresql://db:5432/meubanco
      - DB_USER=usuario
      - DB_PASS=senha123

      # Redis config (fixed for container internal network)
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis

      # Security & External APIs injection
      - JWT_SECRET=secret_password
      - GOOGLE_CLIENT_ID=testete
      - GOOGLE_CLIENT_SECRET=teste
      - RESEND_API_KEY=teste
      - MAIL_FROM=teste

      # ---  Web Push ---
      - VAPID_PUBLIC_KEY=BPflBBkWNQarTPMxmzW1Uz0H1U0GOIW4RW79Gd3eCgVSWdtBvfHiy6U2fzQotYvjSHzAP5MY2YCHpjHqfhqUyn8
      - VAPID_PRIVATE_KEY=WuzeO7_abRynkhcw5wgFLbgkFUz4kyfzN0cl4O3WvXc
      - VAPID_SUBJECT=mailto:suporte@clickfila.com.br

      # ---  ASAAS API ---
      - ASAAS_API_URL=https://sandbox.asaas.com/api/v3
      - ASAAS_API_KEY=sua_chave_do_asaas_aqui

      - DOCKER_COMPOSE_ENABLED=true
      - SWAGGER_ENABLED=true


  alloy:
    image: grafana/alloy:latest
    container_name: clickfila-alloy
    restart: unless-stopped
    profiles:
      - "metrics"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_USERNAME=${GRAFANA_USERNAME}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    extra_hosts:
          - "api:host-gateway"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
